iag_file:
    resource: "@IagFileBundle/Resources/config/routing.yml"
    prefix:   /

iag_menu:
    resource: "@IagMenuBundle/Resources/config/routing.yml"
    prefix:   /

iag_home:
    resource: "@IagHomeBundle/Resources/config/routing.yml"
    prefix:   /

iag_local:
    resource: "@IagLocalBundle/Resources/config/routing.yml"
    prefix:   /

iag_infra:
    resource: "@IagInfraBundle/Resources/config/routing.yml"
    prefix:   /

iag_switch:
    resource: "@IagSwitchBundle/Resources/config/routing.yml"
    prefix:   /

iag_ip:
    resource: "@IagIpBundle/Resources/config/routing.yml"
    prefix:   /

iag_vlan:
    resource: "@IagVlanBundle/Resources/config/routing.yml"
    prefix:   /

iag_user:
    resource: "@IagUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /secure_area/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#sonata
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin