voiceporta:
    path:     /
    defaults: { _controller: "IagInfraBundle:VoicePorta:index" }

voiceporta_show:
    path:     /{id}/show
    defaults: { _controller: "IagInfraBundle:VoicePorta:show" }

voiceporta_new:
    path:     /new
    defaults: { _controller: "IagInfraBundle:VoicePorta:new" }

voiceporta_create:
    path:     /create
    defaults: { _controller: "IagInfraBundle:VoicePorta:create" }
    requirements: { _method: post }

voiceporta_edit:
    path:     /{id}/edit
    defaults: { _controller: "IagInfraBundle:VoicePorta:edit" }

voiceporta_update:
    path:     /{id}/update
    defaults: { _controller: "IagInfraBundle:VoicePorta:update" }
    requirements: { _method: post|put }

voiceporta_delete:
    path:     /{id}/delete
    defaults: { _controller: "IagInfraBundle:VoicePorta:delete" }
    requirements: { _method: post|delete }
